### ISSUE TITLE
unreal 4.14

### ISSUE THREAD

**Issue by DeadMaroz** [devtodev-analytics/unreal-sdk#1]
Hi. Is it compatible with UE 4.14? I am doing according this manual: https://www.devtodev.com/help/141/analytics_integration/ , but it shows error and proposes me to rebiuld from source.

**Comment by Skazochnij** [comment]
Hello, with last test version UE4 4.14.3 our plugin works correctly. Please provide details about error messages.

**Comment by DeadMaroz** [comment]
I recieve this error trying to add this plugin. The same with blank c++ project. I have tried 4.14 and 1.14.3 versions.  
![error](https://cloud.githubusercontent.com/assets/24796954/22023036/362d89c6-dccd-11e6-9e63-3189fc0aea71.PNG)

**Comment by Skazochnij** [comment]
Сan you copy the logs in the assembly, which are displayed by pressing the "Show Logs"?
![starting build 2017-01-18 11-56-56](https://cloud.githubusercontent.com/assets/3314943/22059396/507365be-dd75-11e6-9af7-f12a32f4e07e.png)
