### ISSUE TITLE
Upgrade to 4.23

### ISSUE THREAD

**Issue by lcdlv** [devtodev-analytics/unreal-sdk#3]
Hi! You can upgrade the plugin to 4.23?
Thanks in advance!

**Comment by lcdlv** [comment]
Hellooooo....

**Comment by rtalibullin** [comment]
Hi! Sorry for delay. We are working on uptdae, it will be available soon.

**Comment by lcdlv** [comment]
Thanks for answer!

**Comment by rtalibullin** [comment]
Plugin was upgraded to 4.23
