### ISSUE TITLE
Several errors on 4.23 release!

### ISSUE THREAD

**Issue by lcdlv** [devtodev-analytics/unreal-sdk#4]
In devtodev.uplugin there is an error on line 26, I uploaded a file with the missed comma.
Other problem is after open the project, the plugin fails. I add an image.

![Screenshot_2](https://user-images.githubusercontent.com/7636017/66579502-4d1bef00-eb53-11e9-813c-9d62b27aa495.png)
![Screenshot_3](https://user-images.githubusercontent.com/7636017/66579504-4db48580-eb53-11e9-8c86-d6d0e821a95a.png)

**Comment by rtalibullin** [comment]
Thank you for your feedback! These issues where fixed in version 1.3.2.
