### ISSUE TITLE
Error when include DTDAnalyticsBlueprintFunctionLibrary.h

### ISSUE THREAD

**Issue by GloryOfNight** [devtodev-analytics/unreal-sdk#5]
Hi! 
I have C++ Unreal project and I want to include analytics function library to my file. But on include:

> #include "devtodev/Public/DTDAnalyticsBlueprintFunctionLibrary.h"

I get this compile error:

> Error	C2139 'FAnalyticsEventAttr': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_trivially_destructible'	BombaNino	C:\Program Files\Epic Games\UE_4.21\Engine\Source\Runtime\Core\Public\Templates\IsTriviallyDestructible.h	18	

also. I want to mention. 
This official [Documentation](https://www.devtodev.com/help/141/analytics_integration/) do not have any instructions for C++ Analytics usage, but has code samples (some of them seems old).

**Comment by rtalibullin** [comment]
Hi! 
Class FAnalyticsEventAttr is Unreal Engine class and we don't actually control it. You use UE version 4.21 for build, however plugin was built with 4.23. It could be origin of the issue. Could you try to convert your project to 4.23 and try again?

**Comment by GloryOfNight** [comment]
Changing project version for us is not a option. I guess I'll just start using DTDWrapper that has raw functions in in. 
Also. I checked 1.2.1 release that should be designed for 4.21, it's has the same issue with FAnalyticsEventAttr.

**Comment by GloryOfNight** [comment]
Please check pull request #6. There should be fixed that issue.
